### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by Nordes** [beevelop/docker-shields#10]
Hi @beevelop , 
I don't know if I am doing something wrong, but basically I pulled the image and then tried to start it. But when I do I have the following error:

```
Starting samples_shields_1 ... done
Creating samples_varnish_1 ... done
Attaching to samples_shields_1, samples_varnish_1
shields_1  | /opt/shields/server.js:135
shields_1  | async function stop() {
shields_1  |       ^^^^^^^^
shields_1  |
shields_1  | SyntaxError: Unexpected token function
shields_1  |     at createScript (vm.js:56:10)
shields_1  |     at Object.runInThisContext (vm.js:97:10)
shields_1  |     at Module._compile (module.js:549:28)
shields_1  |     at Object.Module._extensions..js (module.js:586:10)
shields_1  |     at Module.load (module.js:494:32)
shields_1  |     at tryModuleLoad (module.js:453:12)
shields_1  |     at Function.Module._load (module.js:445:3)
shields_1  |     at Module.runMain (module.js:611:10)
shields_1  |     at run (bootstrap_node.js:394:7)
shields_1  |     at startup (bootstrap_node.js:160:9)
samples_shields_1 exited with code 1
```

My docker-compose file look like the following:
```
version: '3'
services:
  shields:
    image: beevelop/shields
    environment:
      - INFOSITE:http://shields.local
    restart: always
  varnish:
    image: beevelop/varnish
    environment:
      - VIRTUAL_HOST:shields.local
    links:
    - "shields:backend"
    restart: always
```

Thank you for your assistance.
